# Generated by Django 6.0.3 on 2026-03-30 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Категория',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('описание', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Производитель',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100)),
                ('страна', models.CharField(max_length=100)),
                ('описание', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Корзина',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='корзина', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Товар',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200)),
                ('описание', models.TextField()),
                ('фото_товара', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('цена', models.DecimalField(decimal_places=2, max_digits=10)),
                ('количество_на_складе', models.IntegerField()),
                ('категория', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='товары', to='shop.категория')),
                ('производитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='товары', to='shop.производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ЭлементКорзины',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField()),
                ('корзина', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы', to='shop.корзина')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='элементы_корзины', to='shop.товар')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
    ]
